services:
  proxy:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - root_service
      - 1993_service
      - 2000_service

  root_service:
    build: ./root
    container_name: root_service_container
    develop:
      watch:
        - path: ./root
          target: /usr/share/nginx/html
          action: sync

  1993_service:
    build: ./1993
    container_name: 1993_service_container

  2000_service:
    build: ./2000
    container_name: 2000_service_container

